default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_bin
  pool: 5
  timeout: 5000
  username: <%= ENV["MYSQL_USERNAME"] || "app" %>
  password: <%= ENV["MYSQL_PASSWORD"] || "password" %>
  host: <%= ENV["MYSQL_HOST"] || "127.0.0.1" %>
  port: <%= ENV["MYSQL_PORT"] || "3306" %>

development:
  <<: *default
  database: awesome_events


test:
  <<: *default
  database: awesome_events_test

production:
  <<: *default
  database: postgresql
  encoding: unicode
  pool: 5
